### ISSUE TITLE
License

### ISSUE THREAD

**Issue by grst** [gokceneraslan/fit_nbinom#5]
Hi @gokceneraslan, 

do you mind if I include this code under BSD licence in [scirpy](https://github.com/icbi-lab/scirpy)? 
Or do you happen to know something like that is implemented in the usual suspect packages by now? I only found [statsmodels.discrete.discrete_model.NegativeBinomial](https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.NegativeBinomial.html), but it seems to be a noise model for a GLM and I couldn't make it work to just fit my distribution. 

Cheers, 
Gregor

**Comment by gokceneraslan** [comment]
Of course, no problem.
